CREATE TABLE blogs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    body TEXT NOT NULL
);

INSERT INTO blogs (id, title, url, body) 
VALUES (1, 'my first blog post', 'first_blog_entry', 'lorem ipsum dolor');
